name = "opener-rate"
main = "worker/index.ts"
compatibility_date = "2026-02-10"
compatibility_flags = ["nodejs_compat"]
workers_dev = false

[site]
bucket = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "opener-rate-db"
database_id = "3c3c9491-0401-4107-b5ee-99a7dbfb279b"
migrations_dir = "drizzle"

[vars]
APP_ORIGIN = "https://opener-rate.miyauchidp.dev"

[[routes]]
pattern = "opener-rate.miyauchidp.dev"
custom_domain = true
